- block: # get join command

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command_raw

  - name: set join command
    set_fact:
      join_command: "{{ join_command_raw.stdout_lines[0] }}"

  when: ansible_nodename == "k8s-master"

- block: # Joining nodes

  - name: join cluster
    shell: "{{ hostvars['k8s-master'].join_command }} --cri-socket unix:///var/run/cri-dockerd.sock >> node_joined.txt"

  when: inventory_hostname in groups["worker"]
