- block: # Creating a cluster with kubeadm

  - name: control-plaine(master) configuration
    shell:
      cmd: |
        kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///var/run/cri-dockerd.sock >> cluster_initialized.txt
        mkdir -p $HOME/.kube
        cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

  - name: install Pod network
    shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

  - name: Setting up kubectl command autocomplete
    shell:
      cmd: |
        apt-get install bash-completion -y
        source <(kubectl completion bash)
        echo "source <(kubectl completion bash)" >> ~/.bashrc

  - name: Installing etcd - Installing etcd on the control-plane (master)
    shell:
      cmd: |
        export RELEASE=$(curl -s https://api.github.com/repos/etcd-io/etcd/releases/latest|grep tag_name | cut -d '"' -f 4)
        wget https://github.com/etcd-io/etcd/releases/download/${RELEASE}/etcd-${RELEASE}-linux-amd64.tar.gz
        tar xf etcd-${RELEASE}-linux-amd64.tar.gz
        cd etcd-${RELEASE}-linux-amd64
        mv etcd etcdctl etcdutl /usr/local/bin