- block: # Installing kubeadm

  - name: Install required system packages
    apt:
      update_cache: yes
      name:
      - apt-transport-https
      - ca-certificates
      - curl
      state: latest
  
  - name: Download the Google Cloud public signing key
    shell:
      cmd: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list
        
  - name: Update apt package index, install kubelet, kubeadm and kubectl
    apt:
      update_cache: yes
      name:
      - kubelet
      - kubeadm
      - kubectl
      state: latest

  - name: apt-mark hold
    shell: apt-mark hold kubelet kubeadm kubectl
    register: apt_mark_output

  - debug:
      var: apt_mark_output.stdout_lines
