- block: # Install container runtime

  - name: Install required system packages
    apt:
      update_cache: yes
      name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: latest

  - name: Add Docker GPG apt Key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present

  - name: Update apt and install Docker Engine
    apt:
      update_cache: yes
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      state: latest

- block: # install cri-docker

  - name: Install cri-docker
    shell:
      cmd: |
        wget https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.1/cri-dockerd_0.3.1.3-0.debian-bullseye_amd64.deb
        dpkg -i cri-dockerd_0.3.1.3-0.debian-bullseye_amd64.deb
        ls -l  /var/run/cri-dockerd.sock
    register: command_output

  - debug:
      var: command_output.stdout_lines
